apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjMjFwY201dmRpMWhiR1Y0TFRRd05EcG5hSEJmVFdKWFJraFRVVWROU0cxamRucEdiMmR3VFROemNEVjVNVzUwWlRKdU1XTk9lbk16IgoJCX0KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZWZhdWx0Igp9
type: kubernetes.io/dockerconfigjson
